# Generated by Django 4.2.5 on 2023-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(default=None, max_length=40)),
                ('produto_e_servicos', models.TextField(default=None, max_length=40)),
                ('telefone', models.TextField(default=None, max_length=11)),
                ('email', models.TextField(default=None, max_length=50)),
            ],
        ),
    ]
